### ISSUE TITLE
Seeking in certain places in Rush E 2 causes audible weirdness.

### ISSUE THREAD

**Issue by StratusFearMe21** [arduano/wasabi#28]
When seeking in certain places in Rush E 2, it sounds to me like it's not resetting the sustain pedal. I've sent the MIDI file that's causing this bug to @arduano through Discord. I can't put the MIDI file here because Rush E 2 is a payed MIDI file.

https://user-images.githubusercontent.com/57533634/231650307-7c68d926-5711-4ad8-b4ba-defc4752043c.mp4

Above is a video of me performing the bug.

**Comment by StratusFearMe21** [comment]
Notice how to first time I seek to the quiet part, it's quiet. As it should be. But when I seek to the end of the song, and then back to the quiet part, it sounds like some notes are being held down. It's not just the end of the song that does this just to be clear, it's just the easiest to perform the bug on

**Comment by arduano** [comment]
@MyBlackMIDIScore xsynth issue? I think we don't reset the pedal when we send a synth reset event do we

**Comment by arduano** [comment]
I'm currently AFK but I could look at it later if you don't beat me to it

**Comment by MyBlackMIDIScore** [comment]
> @MyBlackMIDIScore xsynth issue? I think we don't reset the pedal when we send a synth reset event do we

Here is the code in XSynth that handles the resetting.
[https://github.com/arduano/xsynth/blob/4be1c7b342abb1c815f3224cfe99bd05a4e7043d/core/src/channel/mod.rs#L428](https://github.com/arduano/xsynth/blob/4be1c7b342abb1c815f3224cfe99bd05a4e7043d/core/src/channel/mod.rs#L428)
It does also reset the damper.

It is most likely a Wasabi issue not sending the reset event always when needed, because I have also noticed this happening on other CC controls too, like panning.

I think the issue is in the threads created in the `spawn_playback` functions in Wasabi ([Here](https://github.com/arduano/wasabi/blob/b8e83083a342c52a7bed13ccbdf6488288b19af5/src/midi/ram/audio_player.rs#L36) and [Here](https://github.com/arduano/wasabi/blob/b8e83083a342c52a7bed13ccbdf6488288b19af5/src/midi/live/audio_player.rs#L36)).

I will do some tests by calling the reset function in more places (eg. when seeking) to see if this helps.

**Comment by MyBlackMIDIScore** [comment]
@StratusFearMe21 Can you try the `fix-cc-resetting` branch from the [PR](https://github.com/arduano/wasabi/pull/29) I linked above to see if this fixes the issue?

**Comment by StratusFearMe21** [comment]
Unfortunately, your PR doesn't fix the issue for me

**Comment by StratusFearMe21** [comment]
And just a heads up, the latest commit of `midi-toolkit-rs` isn't compiling due to the lack of `#![feature(impl_trait_in_assoc_type)]` at the crate's root

**Comment by StratusFearMe21** [comment]
I've just sent the offending MIDI file to @MyBlackMIDIScore as well

**Comment by StratusFearMe21** [comment]
Creating a button that calls `synth.reset()`, and clicking it when the problem arises does not fix the issue either

**Comment by MyBlackMIDIScore** [comment]
@StratusFearMe21 Please try the latest commit from the same branch. It should be fixed now, I just want to make sure.

**Comment by StratusFearMe21** [comment]
@MyBlackMIDIScore, yep! It's fixed. I updated my build to the latest version of XSynth, and it doesn't happen anymore!
